### ISSUE TITLE
TypeError: e.slice().map is not a function error after updating to version 0.13

### ISSUE THREAD

**Issue by Lextum** [ActivityWatch/activitywatch#1067]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Ubuntu 22.04
- **ActivityWatch version**: 0.13 (deb Installation)
## Describe the bug
Since the new version (updated from 0.12.2 to 0.13) the WebUI does not work in Firefox anymore. There is an error 

> TypeError: e.slice().map is not a function. See dev console (F12) and/or server logs for more info.

![image](https://github.com/ActivityWatch/activitywatch/assets/5988613/d0b2d440-f299-413d-bf8f-e0dfcb48b916)
![image](https://github.com/ActivityWatch/activitywatch/assets/5988613/d130a873-b6ea-4caa-933c-178440fa90f2)

Opening the WebUI and everything is fine.

## To Reproduce
- Update to the currently newest version 0.13
- starting ActivityWatch via qt (e.g. /opt/activitywatch/aw-qt)
- opening ActivityWatch in firefox (http://localhost:5600/#/activity/HOSTNAME/view/)

### Updating
While updating I found that you provide a deb package. I used the generic Linux zip file and started the binary from their. 

I installed the deb file and started the application new from the `/opt/activitywatch/aw-qt` instead of `$HOME/.local/bin/activitywatch/aw-qt`

## Expected behavior
- Do not show the error, show the Activity screen

## Documentation
I added some screenshots above, I hope this is fine.

## Additional context
Maybe another bug or mistake I made, but I enable since the update and/or enable the rust server my categorization is gone. I don't think this i related to the firefox bug.

**Comment by avi-cenna** [comment]
I am getting the same issue in Chrome after upgrading to v0.13. The issue pops up both with aw-server and aw-server-rust. However, in the rust version I can at least see something in the Timeline. Here is a screenshot of the Dev Tools panel showing the error.

![Screenshot 2024-06-04 at 5 27 46 PM](https://github.com/ActivityWatch/activitywatch/assets/47500890/db3c24be-c5ae-4fe0-8248-5dfbb7b7092c)

**Comment by bbrendon** [comment]
Doesn't work in Brave either.

TypeError: e.slice(...).map is not a function. See dev console (F12) and/or server logs for more info.

**Comment by bbrendon** [comment]
Clearing  your cookies for localhost seems to fix this.

**Comment by avi-cenna** [comment]
I confirm that clearing cookies resolved the issue. FWIW, here are the instructions to clear cookies for a single website in Chrome.

![Screenshot 2024-06-05 at 10 53 02 AM](https://github.com/ActivityWatch/activitywatch/assets/47500890/67b440fa-3a20-433c-a013-e6cbd3c27d25)

**Comment by ErikBjare** [comment]
Seems the issue is here: https://github.com/ActivityWatch/aw-webui/blob/05c25c98b172fcb72e2ae7cbf40be6bc77526c65/src/util/classes.ts#L109

The exact line and surrounding chunk hasn't changed in 3+ years, so it's probably an issue where `classes` is `null`/`undefined` for some reason. I can't really figure out why that might be, though.

**Comment by avi-cenna** [comment]
It seems like my categories were wiped out after I cleared the cookies. Not a big deal though because my rules weren't that sophisticated anyway.

**Comment by diegonz** [comment]
Yo can save you rules before clean your cookies. Go to: 

1. Developer tools (F12)
2. Application tab
3. Storage
4. Local Storage
5. http://localhost:5600

![image](https://github.com/ActivityWatch/activitywatch/assets/7355149/d4deba8e-eea5-4828-a08b-926f1d235068)

From the bottom part of the screen where you can see the rules _(sorry I've already deleted my cookies)_, right click, then select copy object, then use your clipboard to fill the categories array:

```javascript
{
  "categories": [
    {
      "name": [
        "Work"
      ],
      "rule": {
        "type": "regex",
        "regex": "Google Docs|libreoffice|ReText"
      },
      "data": {
        "color": "#0F0"
      },
      "id": 0
    },
    {
      "name": [
        "Work",
        "Programming"
      ],
      "rule": {
        "type": "regex",
        "regex": "GitHub|Stack Overflow|BitBucket|Gitlab|vim|Spyder|kate|Ghidra|Scite"
      },
      "id": 1
    }
  ]
}
``` 

Hope it helps someone that has lost access to settings page due to vue errors as it happened to me.

**Comment by ErikBjare** [comment]
I really wonder how many users will face this issue when upgrading...

@avi-cenna I edited in a warning in https://github.com/ActivityWatch/activitywatch/issues/1067#issuecomment-2148581034 so people will hopefully realize. Any workaround would include correctly parsing the localStorage settings.

I realized the `e.slice().map` is not a function indicates that type of `e` has a `slice()` but not a `map()` on the resulting type. This probably means that `e` is a string and not an array as it should be, which indicates that `localStorage.categories` might not be parsed into JSON.

**Comment by Lextum** [comment]
Thanks for the fast response and analyze. It didn't even think to check the local storage.

I was able to restore my categories and the problem with manually exporting the categories from local storage and reimported via get UI. Which likes it is working so far.

I adapted the export to be similar to the JSON generated by the export function. `{  "categories": [ Export from local storage] }`

For me the problem is fixed. @ErikBjare should I close this issue or would like to keep it open for other users?

**Comment by ErikBjare** [comment]
Lets keep the issue open until I've had time to merge a fix.

**Comment by ErikBjare** [comment]
I think I have a fix in https://github.com/ActivityWatch/aw-webui/pull/583, but I would appreciate a review/test from someone.

**Comment by BelKed** [comment]
Manually verified, everything works perfectly :)
https://github.com/ActivityWatch/aw-webui/pull/583#pullrequestreview-2107924431
